### ISSUE TITLE
transformation throw _iteratorError

### ISSUE THREAD

**Issue by vikor** [mohebifar/xto6#36]
Precondition: Windows 7 SP2, node 0.10.29
The installation completed successfully, tested the example from xto6.js.org.
Next log obtained:

>xto6 es5.js -o es6.js

\nodejs\node_modules\xto6\lib\transformation\classes.js:124
            throw _iteratorError;
                  ^
ReferenceError: Symbol is not defined
  at Controller.classMaker (\nodejs\node_modules\xto6\lib\transformation\classes.js:87:40)
  at Controller.__execute (\nodejs\node_modules\xto6\node_modules\estraverse\estraverse.js:399:31)
  at Controller.traverse (\nodejs\node_modules\xto6\node_modules\estraverse\estraverse.js:497:28)
  at Object.traverse (\nodejs\node_modules\xto6\node_modules\estraverse\estraverse.js:709:27)
  at module.exports (\nodejs\node_modules\xto6\lib\transformation\classes.js:26:14)
  at Transformer.applyTransformation (\nodejs\node_modules\xto6\lib\transformer.js:118:9)
  at Transformer.applyTransformations (\nodejs\node_modules\xto6\lib\transformer.js:131:16)
  at module.exports (\nodejs\node_modules\xto6\bin\file.js:14:15)
  at Object.<anonymous> (\nodejs\node_modules\xto6\bin\index.js:36:3)
  at Module._compile (module.js:456:26)
  at Object.Module._extensions..js (module.js:474:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:312:12)
  at Function.Module.runMain (module.js:497:10)
  at startup (node.js:119:16)
  at node.js:906:3

This error not reproduced with node v0.11.22. It's OK.

**Comment by mdibaiee** [comment]
See #34
