### ISSUE TITLE
Transpiling commonJS files causes exception

### ISSUE THREAD

**Issue by danielmoore** [mohebifar/xto6#37]
xto6 version: 1.1.0-alpha
node version: 0.12.2

Transpiling this file:

```js
'use strict'

module.exports = function () {
  return 'hello, world!';
};
```

Results in:

```
C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\lib\transformation\let.js:25
    declarations[left].kind = "let";
                            ^
TypeError: Cannot set property 'kind' of undefined
  at Controller.replaceVar (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\lib\transformation\let.js:25:29)
  at Controller.__execute (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\node_modules\estraverse\estraverse.js:399:31)
  at Controller.traverse (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\node_modules\estraverse\estraverse.js:497:28)
  at Object.traverse (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\node_modules\estraverse\estraverse.js:709:27)
  at module.exports (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\lib\transformation\let.js:8:14)
  at Transformer.applyTransformation (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\lib\transformer.js:118:9)
  at Transformer.applyTransformations (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\lib\transformer.js:131:16)
  at module.exports (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\bin\file.js:14:15)
  at Object.<anonymous> (C:\Users\daniel\AppData\Roaming\npm\node_modules\xto6\bin\index.js:36:3)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

This might be related to #31

**Comment by mohebifar** [comment]
Fixed. Thanks for the report.
