### ISSUE TITLE
Error: Cannot find module './block-statement.js'

### ISSUE THREAD

**Issue by mbixby** [mohebifar/xto6#4]
```
module.js:340
    throw err;
          ^
Error: Cannot find module './block-statement.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/xto6/lib/syntax/function-expression.js:15:38)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by pornel** [comment]
The workaround is to run `grunt` in the module's directory.

**Comment by pascalopitz** [comment]
Got the same ... not sure what running grunt in module's directory refers to exactly, but installing grunt locally or globally didn't make a difference.

**Comment by mohebifar** [comment]
I added some missing es5 scripts to the source files.
